-- 아래는 STUDENT 테이블에 대한 구조를 보여줍니다. 테이블을 수정하실 필요는 없습니다.
DESC STUDENT;

-- 학생들의 수학, 물리, 화학 점수의 총합을 기준으로 백분율 순위와 누적 백분율을 조회하는 쿼리를 작성하세요.
SELECT ID, MATH, PHYSICS, CHEMISTRY,
(MATH + PHYSICS + CHEMISTRY) AS SCORE_SUM,

PERCENT_RANK() OVER(ORDER BY SCORE_SUM DESC) AS PERCENT_RANK,

CUME_DIST() OVER(ORDER BY SCORE_SUM DESC) AS CUME_DIST

FROM STUDENT
ORDER BY SCORE_SUM DESC;
