-- 아래는 STUDENT, COURSE_SCORE 테이블에 대한 구조를 보여줍니다. 테이블을 수정하실 필요는 없습니다.
DESC STUDENT;
DESC COURSE_SCORE;


-- 수업이름과 학과에 대해서 ROLLUP 을 이용하여 평균 점수를 구해보세요.
SELECT COURSE_NAME, DEPARTMENT, AVG(SCORE)
FROM STUDENT a INNER JOIN COURSE_SCORE b 
on a.ID = b.STUDENT_ID
GROUP BY b.COURSE_NAME, a.DEPARTMENT WITH ROLLUP
;
